import type { Metadata } from "next";
import { Providers } from "./providers";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import Navmenu from "../components/ui/navmenu"; // Make sure the path is correct

import { cn } from "@/lib/utils";
import { NextUIProvider } from "@nextui-org/react";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased  bg-white",
          fontSans.variable
        )}
      >
        <header className="fixed top-0 w-full z-50">
          <Navmenu />
        </header>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
